### ISSUE TITLE
Install Laravel

### ISSUE THREAD

**Issue by teadinja** [teadinja/laravel-playground#1]
Help me learn about Laravel first by installing it.

**Comment by tomhorvat** [comment]
You can install Laravel via composer:

https://laravel.com/docs/5.7#installing-laravel

**Comment by tomhorvat** [comment]
I created a pull request #2 

Once merged you can clone it locally and have laravel installed.

**Comment by tomhorvat** [comment]
In pull #5 moved Laravel installation to root.

**Comment by teadinja** [comment]
thx 👍
